/** ISO 3166-1 alpha-2 codes with display names for the Storefront country picker. Provider support is decided by the Quote. */
export const COUNTRIES: ReadonlyArray<readonly [string, string]> = [
  ['AT', 'Austria'],
  ['AU', 'Australia'],
  ['BE', 'Belgium'],
  ['BG', 'Bulgaria'],
  ['BR', 'Brazil'],
  ['CA', 'Canada'],
  ['CH', 'Switzerland'],
  ['CZ', 'Czechia'],
  ['DE', 'Germany'],
  ['DK', 'Denmark'],
  ['EE', 'Estonia'],
  ['ES', 'Spain'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GB', 'United Kingdom'],
  ['GR', 'Greece'],
  ['HR', 'Croatia'],
  ['HU', 'Hungary'],
  ['IE', 'Ireland'],
  ['IL', 'Israel'],
  ['IT', 'Italy'],
  ['JP', 'Japan'],
  ['KR', 'South Korea'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['LV', 'Latvia'],
  ['MX', 'Mexico'],
  ['NL', 'Netherlands'],
  ['NO', 'Norway'],
  ['NZ', 'New Zealand'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['RO', 'Romania'],
  ['SE', 'Sweden'],
  ['SG', 'Singapore'],
  ['SI', 'Slovenia'],
  ['SK', 'Slovakia'],
  ['US', 'United States'],
];

/** Countries whose shipping quote needs a state/province code. */
export const STATE_REQUIRED = new Set(['US', 'CA', 'AU']);
